In [ ]:
import torch
import torch.nn.functional as F

In [ ]:
tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = F.softmax(tensor, dim = 0) # 확률 0~1사이의 값으로 변환
h_tensor

tensor([0.3458, 0.4224, 0.2318])

In [ ]:
y = torch.randint(5, (10, 5))
y_label = y.argmax(dim=1)
y_label

tensor([1, 2, 3, 2, 1, 4, 2, 3, 4, 0])

In [ ]:
torch.nn.functional.one_hot(y_label)
F.one_hot(y_label)

tensor([[0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0]])

## cartesian_prod

In [1]:
import itertools
a = [1, 2]
b = [4, 5]
list(itertools.product(a,b)) 

[(1, 4), (1, 5), (2, 4), (2, 5)]

In [3]:
import torch
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
torch.cartesian_prod(tensor_a, tensor_b) # 모든 경우의 수를 다 출력

tensor([[1, 4],
        [1, 5],
        [2, 4],
        [2, 5]])

## Torch autograd

$$
y = w^2 \\ 
z = 10*y + 50 \\
z = 10*w^2 + 50 
$$

In [17]:
w = torch.tensor(2.0, requires_grad = True)
y = w ** 2
z = 10 * y + 50
z.backward()
w.grad

tensor(40.)

$$ Q = 3a^3 - b^2  $$

In [12]:
a = torch.tensor([2., 3.], requires_grad = True) # 미분을 할지 안할지
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3* a **3 - b**2
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

a.grad

tensor([36., 81.])

In [13]:
b.grad

tensor([-12.,  -8.])

$$ \frac{\partial Q}{\partial a} = 9a^2 $$  

$$ \frac{\partial Q}{\partial b} = -2b $$

In [14]:
a.grad # [2., 3.]

tensor([36., 81.])

In [15]:
b.grad # [6., 4.]

tensor([-12.,  -8.])